import 'package:flutter_test/flutter_test.dart';
import 'package:navalert/core/geo.dart';

/// Phase 2 geometry for the offline route shapes. The shapes are generated by
/// `tool/gen_shapes.py`, so the decoder here must agree exactly with the
/// encoder there — a silent disagreement would draw every jeepney route in the
/// wrong place, which is the kind of fault that looks like bad map data rather
/// than a bug.
void main() {
  group('decodePolyline', () {
    test('decodes the reference example from the Google spec', () {
      // "_p~iF~ps|U_ulLnnqC_mqNvxq`@" -> (38.5,-120.2) (40.7,-120.95) (43.252,-126.453)
      final pts = decodePolyline('_p~iF~ps|U_ulLnnqC_mqNvxq`@');
      expect(pts.length, 3);
      expect(pts[0][0], closeTo(38.5, 1e-5));
      expect(pts[0][1], closeTo(-120.2, 1e-5));
      expect(pts[2][0], closeTo(43.252, 1e-5));
      expect(pts[2][1], closeTo(-126.453, 1e-5));
    });

    test('an empty string decodes to no points', () {
      expect(decodePolyline(''), isEmpty);
    });

    test('truncated input stops cleanly instead of throwing', () {
      // A half-written varint must not crash the map.
      expect(() => decodePolyline('_p~iF~ps|U_ul'), returnsNormally);
    });

    test('decodes a real generated NavAlert shape inside its stored bbox', () {
      // Route 3, "Sta Ana P Faura", as written by tool/gen_shapes.py.
      const poly =
          r'gq_xAsisaVJPYNzMvXj@fAf@PvCfN^f@jCfNrHdh@TtNMlAw@F}JyH_@`@zHrFHjMgLXWcDtHSFjHfGQEuEN~IzBjLuE|J`DlHbUsKfCbGaUpKh@jAXOHPIQ';
      final pts = decodePolyline(poly);
      expect(pts.length, greaterThan(30));
      // The bounding box the generator stored for this route.
      for (final p in pts) {
        expect(p[0], inInclusiveRange(14.5741, 14.5848));
        expect(p[1], inInclusiveRange(120.9818, 121.0181));
      }
    });
  });

  group('distanceToPolylineM', () {
    // A 1 km east-west segment at Manila's latitude.
    final line = [
      [14.5979, 121.0100],
      [14.5979, 121.0193],
    ];

    test('a point on the line is at zero distance', () {
      expect(distanceToPolylineM(14.5979, 121.0150, line), closeTo(0, 1.0));
    });

    test('measures perpendicular distance, not distance to an endpoint', () {
      // Directly above the MIDDLE of the segment: ~111 m north.
      final d = distanceToPolylineM(14.5989, 121.0150, line);
      expect(d, closeTo(111, 5));
    });

    test('clamps to the endpoint when the point is past the segment', () {
      // Well east of the end: distance must be to the endpoint itself.
      final d = distanceToPolylineM(14.5979, 121.0293, line);
      expect(d, closeTo(1077, 30));
    });

    test('an empty path is infinitely far, never zero', () {
      // Must not read as "you are on this route".
      expect(distanceToPolylineM(14.5979, 121.0150, const []),
          equals(double.infinity));
    });

    test('a single-point path still measures', () {
      final d = distanceToPolylineM(14.5979, 121.0100, [
        [14.5979, 121.0193]
      ]);
      expect(d, closeTo(1000, 30));
    });

    test('takes the nearest segment of a multi-segment path', () {
      final zig = [
        [14.5979, 121.0100],
        [14.5979, 121.0193],
        [14.6079, 121.0193],
      ];
      // Nearest to the vertical leg, not the horizontal one.
      expect(distanceToPolylineM(14.6029, 121.0203, zig), lessThan(120));
    });
  });
}
