import 'package:flutter_test/flutter_test.dart';
import 'package:navalert/core/geo.dart';
import 'package:navalert/services/route_shape_service.dart';

/// Phase 2 geometry for the offline route shapes. The shapes are generated by
/// `tool/gen_shapes.py`, so the decoder here must agree exactly with the
/// encoder there — a silent disagreement would draw every jeepney route in the
/// wrong place, which is the kind of fault that looks like bad map data rather
/// than a bug.
void main() {
  group('decodePolyline', () {
    test('decodes the reference example from the Google spec', () {
      // "_p~iF~ps|U_ulLnnqC_mqNvxq`@" -> (38.5,-120.2) (40.7,-120.95) (43.252,-126.453)
      final pts = decodePolyline('_p~iF~ps|U_ulLnnqC_mqNvxq`@');
      expect(pts.length, 3);
      expect(pts[0][0], closeTo(38.5, 1e-5));
      expect(pts[0][1], closeTo(-120.2, 1e-5));
      expect(pts[2][0], closeTo(43.252, 1e-5));
      expect(pts[2][1], closeTo(-126.453, 1e-5));
    });

    test('an empty string decodes to no points', () {
      expect(decodePolyline(''), isEmpty);
    });

    test('truncated input stops cleanly instead of throwing', () {
      // A half-written varint must not crash the map.
      expect(() => decodePolyline('_p~iF~ps|U_ul'), returnsNormally);
    });

    test('decodes a real generated NavAlert shape inside its stored bbox', () {
      // Route 3, "Sta Ana P Faura", as written by tool/gen_shapes.py.
      const poly =
          r'gq_xAsisaVJPYNzMvXj@fAf@PvCfN^f@jCfNrHdh@TtNMlAw@F}JyH_@`@zHrFHjMgLXWcDtHSFjHfGQEuEN~IzBjLuE|J`DlHbUsKfCbGaUpKh@jAXOHPIQ';
      final pts = decodePolyline(poly);
      expect(pts.length, greaterThan(30));
      // The bounding box the generator stored for this route.
      for (final p in pts) {
        expect(p[0], inInclusiveRange(14.5741, 14.5848));
        expect(p[1], inInclusiveRange(120.9818, 121.0181));
      }
    });
  });

  group('distanceToPolylineM', () {
    // A 1 km east-west segment at Manila's latitude.
    final line = [
      [14.5979, 121.0100],
      [14.5979, 121.0193],
    ];

    test('a point on the line is at zero distance', () {
      expect(distanceToPolylineM(14.5979, 121.0150, line), closeTo(0, 1.0));
    });

    test('measures perpendicular distance, not distance to an endpoint', () {
      // Directly above the MIDDLE of the segment: ~111 m north.
      final d = distanceToPolylineM(14.5989, 121.0150, line);
      expect(d, closeTo(111, 5));
    });

    test('clamps to the endpoint when the point is past the segment', () {
      // Well east of the end: distance must be to the endpoint itself.
      final d = distanceToPolylineM(14.5979, 121.0293, line);
      expect(d, closeTo(1077, 30));
    });

    test('an empty path is infinitely far, never zero', () {
      // Must not read as "you are on this route".
      expect(distanceToPolylineM(14.5979, 121.0150, const []),
          equals(double.infinity));
    });

    test('a single-point path still measures', () {
      final d = distanceToPolylineM(14.5979, 121.0100, [
        [14.5979, 121.0193]
      ]);
      expect(d, closeTo(1000, 30));
    });

    test('takes the nearest segment of a multi-segment path', () {
      final zig = [
        [14.5979, 121.0100],
        [14.5979, 121.0193],
        [14.6079, 121.0193],
      ];
      // Nearest to the vertical leg, not the horizontal one.
      expect(distanceToPolylineM(14.6029, 121.0203, zig), lessThan(120));
    });
  });

  /// Trimming a stored shape to the ridden portion. A shape is the WHOLE
  /// route, terminal to terminal — drawing all of it for a short trip runs the
  /// line off both edges of the map, which is exactly what the first on-device
  /// test showed.
  group('trimPolyline', () {
    // A straight west->east chain, ~100 m between vertices.
    final path = [
      for (var i = 0; i < 10; i++) [14.5979, 121.0100 + i * 0.0009]
    ];

    test('keeps only the ridden middle', () {
      final t = trimPolyline(path, 14.5979, 121.0127, 14.5979, 121.0154);
      expect(t.length, lessThan(path.length));
      expect(t.first[1], closeTo(121.0127, 0.0005));
      expect(t.last[1], closeTo(121.0154, 0.0005));
    });

    test('reverses when the commuter rides against the stored direction', () {
      final t = trimPolyline(path, 14.5979, 121.0154, 14.5979, 121.0127);
      expect(t.first[1], greaterThan(t.last[1]),
          reason: 'must run origin -> destination, not the stored order');
    });

    test('returns the whole path when both ends hit the same vertex', () {
      final t = trimPolyline(path, 14.5979, 121.0100, 14.5979, 121.0100);
      expect(t.length, path.length);
    });

    test('a degenerate path is returned untouched', () {
      expect(trimPolyline(const [], 0, 0, 1, 1), isEmpty);
      final one = [
        [14.0, 121.0]
      ];
      expect(trimPolyline(one, 0, 0, 1, 1).length, 1);
    });

    test('endpoints of the trim are the nearest vertices', () {
      expect(nearestVertexIndex(14.5979, 121.0100, path), 0);
      expect(nearestVertexIndex(14.5979, 121.0181, path), 9);
    });
  });

  /// Reading the route name out of a commute-guide step. Matching a shape by
  /// proximity alone drew whichever route ran near both ends of the trip
  /// rather than the one the guide names — on a walking suggestion it drew a
  /// jeepney route nobody was riding.
  group('routeNameFromInstruction', () {
    test('reads the quoted route name RouteEngine writes', () {
      expect(
        routeNameFromInstruction(
            'Ride jeepney "BACLARAN - DAPITAN via TAFT" and alight at Taft Ave'),
        'BACLARAN - DAPITAN via TAFT',
      );
    });

    test('handles a name containing punctuation', () {
      expect(
        routeNameFromInstruction(
            'Ride jeepney "Quiapo (Barbosa) - Santol via Sta. Mesa" and alight'),
        'Quiapo (Barbosa) - Santol via Sta. Mesa',
      );
    });

    test('a walking step names no route', () {
      expect(routeNameFromInstruction('Walk to Anonas Street'), isNull);
      expect(routeNameFromInstruction('Walk to your destination'), isNull);
    });

    test('empty quotes are not a route name', () {
      // Must not become a lookup for "" that matches nothing and looks like a
      // missing shape rather than a malformed step.
      expect(routeNameFromInstruction('Ride jeepney "" and alight'), isNull);
    });

    test('an unquoted instruction yields null rather than a guess', () {
      expect(routeNameFromInstruction('Ride jeepney Baclaran to Dapitan'),
          isNull);
    });
  });

  /// Picking between shapes that share a route name. The bundled feed files
  /// most corridors several times - 798 names carry multiple shapes, covering
  /// 1,622 of 1,711 routes - and the variants genuinely differ. One name was
  /// measured with 342, 287, 13 and 9 point versions; taking the first would
  /// sometimes draw a nine-point stub 12.7 km from the trip.
  group('variantScoreM', () {
    final good = [
      for (var i = 0; i < 10; i++) [14.5979, 121.0100 + i * 0.0009]
    ];
    // A stub near the origin only, nowhere near the destination.
    final stub = [
      [14.5979, 121.0100],
      [14.5979, 121.0105],
    ];

    test('scores the WORSE end, so one good end cannot carry a variant', () {
      final from = [14.5979, 121.0100];
      final to = [14.5979, 121.0181];
      expect(variantScoreM(good, from[0], from[1], to[0], to[1]),
          closeTo(0, 5));
      // The stub sits on the origin but is ~800 m from the destination.
      final stubScore =
          variantScoreM(stub, from[0], from[1], to[0], to[1]);
      expect(stubScore, greaterThan(500));
    });

    test('the fuller variant wins on a real trip', () {
      final from = [14.5979, 121.0118];
      final to = [14.5979, 121.0163];
      expect(variantScoreM(good, from[0], from[1], to[0], to[1]),
          lessThan(variantScoreM(stub, from[0], from[1], to[0], to[1])));
    });

    test('an empty candidate is infinitely bad, never zero', () {
      expect(variantScoreM(const [], 14.6, 121.0, 14.6, 121.01),
          equals(double.infinity));
    });
  });
}
